raise version of grunt-bower-task
I tried these commands to according to the README:

```bash
$ git clone https://github.com/yoichiro/chrome_mysql_admin.git
$ cd chrome_mysql_admin
$ npm install
$ grunt
```

But got this error:

```
Fatal error: Arguments to path.join must be strings
```

By googling, I found node on my machine and grunt-bower-task are incompatible.

Then, I modified the version of the package and make it to build.

Pages I found https://github.com/yatskevich/grunt-bower-task/issues/122

 # My environment

```
> node --version
v0.12.4

> grunt --version
grunt-cli v0.1.13
grunt v0.4.5
```

I might get something wrong because I'm new to node and grunt (and modern JavaScript development).
Thanks in advance.